// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ7Mlq0PdWfy9wU7KcdtNfhJIi0ahktks',
    appId: '1:715144148923:web:bcb44d55cd86de9bd8b69e',
    messagingSenderId: '715144148923',
    projectId: 'resto-pos-alimar',
    authDomain: 'resto-pos-alimar.firebaseapp.com',
    storageBucket: 'resto-pos-alimar.firebasestorage.app',
    measurementId: 'G-7ZL36LLGXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR4CAHbIuXQEOIFW7e3JTOHbNlvgzaawM',
    appId: '1:715144148923:android:891c0c55f884d90cd8b69e',
    messagingSenderId: '715144148923',
    projectId: 'resto-pos-alimar',
    storageBucket: 'resto-pos-alimar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC656rfBAU8-qhPrZFDMEVlQwbhGMtgPQ',
    appId: '1:715144148923:ios:a7d49f0c0a9af48ed8b69e',
    messagingSenderId: '715144148923',
    projectId: 'resto-pos-alimar',
    storageBucket: 'resto-pos-alimar.firebasestorage.app',
    iosBundleId: 'com.example.resto',
  );
}
